name: PHPStan

on:
  push:
  pull_request:

concurrency:
    group: phpstan-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '8.2'
          - '8.3'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'
          coverage: none
          
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github

      - name: "Cache Result cache"
        uses: actions/cache@v4
        with:
          path: .phpstan_cache
          key: "result-cache-${{ matrix.php-version }}-${{ github.run_id }}" # always unique key - always writes a new cache
          restore-keys: |
            result-cache-${{ matrix.php-version }} # same prefix but will always find the latest cache
